quarkus.oidc.provider=
quarkus.oidc.client-id=
quarkus.oidc.credentials.secret=
quarkus.oidc.application-type=web-app
quarkus.http.auth.permission.authenticated.paths=/dashboard/admin, /tokens
quarkus.http.auth.permission.authenticated.policy=authenticated
quarkus.oidc.discovery-enabled=true
quarkus.http.port=8081
quarkus.oidc.authentication.user-info-required=true
quarkus.oidc.authentication.scopes=profile,email